### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by xiaoraocoding** [pbrong/hrms#1]
请问配置文件中怎么有2个sql呢？可以分享一下实现的思路吗？

**Comment by pbrong** [comment]
项目部署时可能会区分线下环境和线上环境，hrms通过系统环境标识'HRMS_ENV'来判断使用哪套配置,HRMS_ENV=prod表明使用的配置文件为config-prod.yaml，具体代码见：
https://github.com/pbrong/hrms/blob/c14661bb852cd36292159ad1552642da472a739a/main.go#L27

**Comment by pbrong** [comment]
没什么问题的话我close这个issue
